service: serverless-aws-swapi

custom:
  stage: ${opt:stage, 'offline'}
  region: ${opt:region, 'us-east-1'}
  prismaEngine:
    offline: "node_modules/.prisma/client/*.node"
    staging: "node_modules/.prisma/client/libquery_engine-rhel*"

  esbuild:
    platform: "node"
    target: node16
    sourcemap: linked
  serverless-offline:
    httpPort: 5000
    noPrependStageInUrl: true
    reloadHandler: true

provider:
  name: aws
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  runtime: nodejs16.x
  memorySize: 512
  timeout: 10
  logRetentionInDays: 90
  logs:
    httpApi: true
  httpApi:
    cors: true

functions:
  app:
    handler: handler.handler
    timeout: 30
    events:
      - httpApi:
          path: "/films"
          method: "*"
      - httpApi:
          path: "/films/{id}"
          method: "*"
      - httpApi:
          path: "/films/pelicula/{titulo}"
          method: "*"
      - httpApi:
          path: "/docs"
          method: "*"

package:
  patterns:
    - "!**/*.test.ts"
    - ${self:custom.prismaEngine.${self:custom.stage}}
    - "node_modules/.prisma/client/schema.prisma"
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-offline